### ISSUE TITLE
Documentation: Add DDEV/Composer Install Instructions

### ISSUE THREAD

**Issue by rgcarr** [farmOS/farmOS.org#77]
**Describe the bug**
It's not clear how to install farmOS using Composer from the documentation. This can be a problem when using DDEV with Colima, as the recommended Docker container approach may not work.

**Recommendation**
Add the following snippet to https://farmos.org/development/environment:

> For certain local environments, installing farmOS by Composer may be more straightforward. The following commands would allow farmOS to be installed in a DDEV container:
```
mkdir farmos-ddev
cd farmos-ddev
ddev config --project-type=drupal9 --docroot=web --create-docroot
ddev start
ddev composer create "farmos/project:2.x-dev"
ddev composer require drush/drush
ddev drush si
```
(HT @wotnak)

**Comment by mstenta** [comment]
Thanks for taking note of the process that worked for you @rgcarr!

I think this would make a great community blog post. See my comment in your forum thread: https://farmos.discourse.group/t/installing-on-ddev-via-composer/1646/6?u=mstenta

I'm going to close this because it's not technically a bug - we don't "officially" support DDEV in our docs. You are of course welcome to use it, and a community blog post would be great if you are interested in documenting it! Or just copying your findings into the forum topic you started would be great - so that it is findable by others in the future - without adding to the docs maintenance.

Hope that all makes sense. :-)

**Comment by rgcarr** [comment]
Thanks @mstenta - makes sense to me

I've worked on a few Drupal-related projects and every one has a slightly different way to engage the community, address issues, discuss problems and move things forward
