### ISSUE TITLE
Update to Gatsby 5

### ISSUE THREAD

**Issue by mstenta** [farmOS/farmOS.org#78]
Issue #75 revealed that some newer Gatsby plugins we want to use require Gatsby 5. We are currently on Gatsby 3.

I tried diving into this to see how hard it might be, and found that the `gatsby-material-ui-components` package (which is a dependency of `gatsby-theme-material-ui`) only supports Gatsby 3 or 4, but not 5: https://github.com/hupe1980/gatsby-theme-material-ui/blob/3dab8327c7f6f9d32adf3fa78127316a00f562eb/packages/gatsby-material-ui-components/package.json#L27

`gatsby-theme-material-ui` hasn't been updated since August 2022, so I wonder if it's no longer maintained? What does that mean for farmOS.org?

**Comment by jgaehring** [comment]
> Issue #75 revealed that some newer Gatsby plugins we want to use require Gatsby 5. We are currently on Gatsby 3.

Hmm, yea, earlier upgrades I've done w/ Gatsby were not super hard but still a PITA, although those were very early versions (v1 to v2 and/or v3) so maybe this won't be as bad.

> `gatsby-theme-material-ui` hasn't been updated since August 2022, so I wonder if it's no longer maintained? What does that mean for farmOS.org?

When I chose Material UI, it was really only intended as a stop-gap between the mkdocs Material theme and a more comprehensive redesign, if not a full rebranding. And imo, Material is really not ideal for farmOS.org, since Material was really intended for Android apps and more dynamic web apps, not general text content like documentation websites and blogs. At the time, however, there was general consensus that maintaining parity with the mkdocs Material theme was acceptable while we worked out how to get content from disparate source repositories, and holding off on the rebranding at least until that was done.

And this is getting out of scope for this issue's focus on Gatsby upgrades, but I do still have the provisional designs for at least some kind of branding based on the styles I've adopted in Field Kit over time plus what I thought might work for farmOS.org. It could be possible to adopt some of that design in a gradual manner in combination with a minimalist CSS framework like [Pico.css](https://picocss.com/) so we don't have to reinvent all the navigational components etc. If its worthwhile I could draft up a more detailed plan for how to go about that.

**Comment by mstenta** [comment]
Thanks for the context @jgaehring! I forgot about the rebranding conversation. That all makes good sense. Perhaps we can talk about these ideas on a future monthly call.

Regarding the Gatsby 5 upgrade specifically, @wotnak opened a PR that seems to work well! https://github.com/farmOS/farmOS.org/pull/79
